package model.dao;

import model.base.BaseEvenementadminDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the evenementadmin table.
 * Any customizations belong here.
 */
public class EvenementadminDAO extends BaseEvenementadminDAO {
}