package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the poster table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="poster"
 */
public abstract class BasePoster  implements Serializable {

	public static String PROP_HEUREPOSTE = "Heureposte";
	public static String PROP_ID = "Id";
	public static String PROP_DATEPOSTE = "Dateposte";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private model.PosterPK _id;

	// fields
	private java.util.Date _heureposte;
	private java.util.Date _dateposte;


	// constructors
	public BasePoster () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePoster (model.PosterPK _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BasePoster (
		model.PosterPK _id,
		java.util.Date _heureposte,
		java.util.Date _dateposte) {

		this.setId(_id);
		this.setHeureposte(_heureposte);
		this.setDateposte(_dateposte);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public model.PosterPK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (model.PosterPK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Heureposte
	 */
	public java.util.Date getHeureposte () {
		return _heureposte;
	}

	/**
	 * Set the value related to the column: Heureposte
	 * @param _heureposte the Heureposte value
	 */
	public void setHeureposte (java.util.Date _heureposte) {
		this._heureposte = _heureposte;
	}


	/**
	 * Return the value associated with the column: dateposte
	 */
	public java.util.Date getDateposte () {
		return _dateposte;
	}

	/**
	 * Set the value related to the column: dateposte
	 * @param _dateposte the dateposte value
	 */
	public void setDateposte (java.util.Date _dateposte) {
		this._dateposte = _dateposte;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BasePoster)) return false;
		else {
			model.base.BasePoster mObj = (model.base.BasePoster) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}