package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the personne table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="personne"
 */
public abstract class BasePersonne  implements Serializable {

	public static String PROP_MOT_DE_PASSE = "MotDePasse";
	public static String PROP_PRENOM = "Prenom";
	public static String PROP_PROFIL = "Profil";
	public static String PROP_EMAIL = "Email";
	public static String PROP_TELEPHONE = "Telephone";
	public static String PROP_ID_PERSONNE = "IdPersonne";
	public static String PROP_LOGIN = "Login";
	public static String PROP_NOM = "Nom";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idPersonne;

	// fields
	private java.lang.String _motDePasse;
	private java.lang.String _profil;
	private java.lang.String _telephone;
	private java.lang.String _login;
	private java.lang.String _nom;
	private java.lang.String _prenom;
	private java.lang.String _email;

	// collections
	private java.util.Set _laureatSet;
	private java.util.Set _internauteSet;
	private java.util.Set _responsableSet;


	// constructors
	public BasePersonne () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePersonne (java.lang.Integer _idPersonne) {
		this.setIdPersonne(_idPersonne);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BasePersonne (
		java.lang.Integer _idPersonne,
		java.lang.String _motDePasse,
		java.lang.String _profil,
		java.lang.String _telephone,
		java.lang.String _login,
		java.lang.String _nom,
		java.lang.String _prenom,
		java.lang.String _email) {

		this.setIdPersonne(_idPersonne);
		this.setMotDePasse(_motDePasse);
		this.setProfil(_profil);
		this.setTelephone(_telephone);
		this.setLogin(_login);
		this.setNom(_nom);
		this.setPrenom(_prenom);
		this.setEmail(_email);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="idPersonne"
     */
	public java.lang.Integer getIdPersonne () {
		return _idPersonne;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idPersonne the new ID
	 */
	public void setIdPersonne (java.lang.Integer _idPersonne) {
		this._idPersonne = _idPersonne;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: motDePasse
	 */
	public java.lang.String getMotDePasse () {
		return _motDePasse;
	}

	/**
	 * Set the value related to the column: motDePasse
	 * @param _motDePasse the motDePasse value
	 */
	public void setMotDePasse (java.lang.String _motDePasse) {
		this._motDePasse = _motDePasse;
	}


	/**
	 * Return the value associated with the column: profil
	 */
	public java.lang.String getProfil () {
		return _profil;
	}

	/**
	 * Set the value related to the column: profil
	 * @param _profil the profil value
	 */
	public void setProfil (java.lang.String _profil) {
		this._profil = _profil;
	}


	/**
	 * Return the value associated with the column: telephone
	 */
	public java.lang.String getTelephone () {
		return _telephone;
	}

	/**
	 * Set the value related to the column: telephone
	 * @param _telephone the telephone value
	 */
	public void setTelephone (java.lang.String _telephone) {
		this._telephone = _telephone;
	}


	/**
	 * Return the value associated with the column: login
	 */
	public java.lang.String getLogin () {
		return _login;
	}

	/**
	 * Set the value related to the column: login
	 * @param _login the login value
	 */
	public void setLogin (java.lang.String _login) {
		this._login = _login;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: prenom
	 */
	public java.lang.String getPrenom () {
		return _prenom;
	}

	/**
	 * Set the value related to the column: prenom
	 * @param _prenom the prenom value
	 */
	public void setPrenom (java.lang.String _prenom) {
		this._prenom = _prenom;
	}


	/**
	 * Return the value associated with the column: email
	 */
	public java.lang.String getEmail () {
		return _email;
	}

	/**
	 * Set the value related to the column: email
	 * @param _email the email value
	 */
	public void setEmail (java.lang.String _email) {
		this._email = _email;
	}


	/**
	 * Return the value associated with the column: LaureatSet
	 */
	public java.util.Set getLaureatSet () {
		return this._laureatSet;
	}

	/**
	 * Set the value related to the column: LaureatSet
	 * @param _laureatSet the LaureatSet value
	 */
	public void setLaureatSet (java.util.Set _laureatSet) {
		this._laureatSet = _laureatSet;
	}
	
	public void addToLaureatSet (Object obj) {
		if (null == this._laureatSet) this._laureatSet = new java.util.HashSet();
		this._laureatSet.add(obj);
	}



	/**
	 * Return the value associated with the column: InternauteSet
	 */
	public java.util.Set getInternauteSet () {
		return this._internauteSet;
	}

	/**
	 * Set the value related to the column: InternauteSet
	 * @param _internauteSet the InternauteSet value
	 */
	public void setInternauteSet (java.util.Set _internauteSet) {
		this._internauteSet = _internauteSet;
	}
	
	public void addToInternauteSet (Object obj) {
		if (null == this._internauteSet) this._internauteSet = new java.util.HashSet();
		this._internauteSet.add(obj);
	}



	/**
	 * Return the value associated with the column: ResponsableSet
	 */
	public java.util.Set getResponsableSet () {
		return this._responsableSet;
	}

	/**
	 * Set the value related to the column: ResponsableSet
	 * @param _responsableSet the ResponsableSet value
	 */
	public void setResponsableSet (java.util.Set _responsableSet) {
		this._responsableSet = _responsableSet;
	}
	
	public void addToResponsableSet (Object obj) {
		if (null == this._responsableSet) this._responsableSet = new java.util.HashSet();
		this._responsableSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BasePersonne)) return false;
		else {
			model.base.BasePersonne mObj = (model.base.BasePersonne) obj;
			if (null == this.getIdPersonne() || null == mObj.getIdPersonne()) return false;
			else return (this.getIdPersonne().equals(mObj.getIdPersonne()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdPersonne()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdPersonne().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}