package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public class BasePosterPK implements Serializable {

	private int hashCode = Integer.MIN_VALUE;

	private model.Emploi _idEmploi;
	private model.Internaute _idInternaute;

	public BasePosterPK () {}
	
	public BasePosterPK (
		model.Emploi _idEmploi,
		model.Internaute _idInternaute) {

		this.setIdEmploi(_idEmploi);
		this.setIdInternaute(_idInternaute);
	}


	public model.Emploi getIdEmploi () {
		return _idEmploi;
	}

	public void setIdEmploi (model.Emploi _idEmploi) {
		hashCode = Integer.MIN_VALUE;
		this._idEmploi = _idEmploi;
	}

	public model.Internaute getIdInternaute () {
		return _idInternaute;
	}

	public void setIdInternaute (model.Internaute _idInternaute) {
		hashCode = Integer.MIN_VALUE;
		this._idInternaute = _idInternaute;
	}

	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.PosterPK)) return false;
		else {
			model.PosterPK mObj = (model.PosterPK) obj;
			if (null != this.getIdEmploi() && null != mObj.getIdEmploi()) {
				if (!this.getIdEmploi().equals(mObj.getIdEmploi())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getIdInternaute() && null != mObj.getIdInternaute()) {
				if (!this.getIdInternaute().equals(mObj.getIdInternaute())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}

	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getIdEmploi()) {
				sb.append(this.getIdEmploi().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getIdInternaute()) {
				sb.append(this.getIdInternaute().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}

}