package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the responsable table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="responsable"
 */
public abstract class BaseResponsable  implements Serializable {

	public static String PROP_TYPE_RESPONSABILITE = "TypeResponsabilite";
	public static String PROP_ID_PERSONNE = "IdPersonne";
	public static String PROP_ID_RESPONSABLE = "IdResponsable";
	public static String PROP_STRUCTURE = "Structure";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idResponsable;

	// fields
	private java.lang.String _typeResponsabilite;
	private java.lang.String _structure;

	// many to one
	private model.Personne _idPersonne;

	// collections
	private java.util.Set _evenementadminSet;
	private java.util.Set _messagemailSet;


	// constructors
	public BaseResponsable () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseResponsable (java.lang.Integer _idResponsable) {
		this.setIdResponsable(_idResponsable);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseResponsable (
		java.lang.Integer _idResponsable,
		model.Personne _idPersonne,
		java.lang.String _typeResponsabilite,
		java.lang.String _structure) {

		this.setIdResponsable(_idResponsable);
		this.setIdPersonne(_idPersonne);
		this.setTypeResponsabilite(_typeResponsabilite);
		this.setStructure(_structure);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="idResponsable"
     */
	public java.lang.Integer getIdResponsable () {
		return _idResponsable;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idResponsable the new ID
	 */
	public void setIdResponsable (java.lang.Integer _idResponsable) {
		this._idResponsable = _idResponsable;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: typeResponsabilite
	 */
	public java.lang.String getTypeResponsabilite () {
		return _typeResponsabilite;
	}

	/**
	 * Set the value related to the column: typeResponsabilite
	 * @param _typeResponsabilite the typeResponsabilite value
	 */
	public void setTypeResponsabilite (java.lang.String _typeResponsabilite) {
		this._typeResponsabilite = _typeResponsabilite;
	}


	/**
	 * Return the value associated with the column: structure
	 */
	public java.lang.String getStructure () {
		return _structure;
	}

	/**
	 * Set the value related to the column: structure
	 * @param _structure the structure value
	 */
	public void setStructure (java.lang.String _structure) {
		this._structure = _structure;
	}


	/**
     * @hibernate.property
     *  column=idPersonne
	 * not-null=true
	 */
	public model.Personne getIdPersonne () {
		return this._idPersonne;
	}

	/**
	 * Set the value related to the column: idPersonne
	 * @param _idPersonne the idPersonne value
	 */
	public void setIdPersonne (model.Personne _idPersonne) {
		this._idPersonne = _idPersonne;
	}


	/**
	 * Return the value associated with the column: EvenementadminSet
	 */
	public java.util.Set getEvenementadminSet () {
		return this._evenementadminSet;
	}

	/**
	 * Set the value related to the column: EvenementadminSet
	 * @param _evenementadminSet the EvenementadminSet value
	 */
	public void setEvenementadminSet (java.util.Set _evenementadminSet) {
		this._evenementadminSet = _evenementadminSet;
	}
	
	public void addToEvenementadminSet (Object obj) {
		if (null == this._evenementadminSet) this._evenementadminSet = new java.util.HashSet();
		this._evenementadminSet.add(obj);
	}



	/**
	 * Return the value associated with the column: MessagemailSet
	 */
	public java.util.Set getMessagemailSet () {
		return this._messagemailSet;
	}

	/**
	 * Set the value related to the column: MessagemailSet
	 * @param _messagemailSet the MessagemailSet value
	 */
	public void setMessagemailSet (java.util.Set _messagemailSet) {
		this._messagemailSet = _messagemailSet;
	}
	
	public void addToMessagemailSet (Object obj) {
		if (null == this._messagemailSet) this._messagemailSet = new java.util.HashSet();
		this._messagemailSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseResponsable)) return false;
		else {
			model.base.BaseResponsable mObj = (model.base.BaseResponsable) obj;
			if (null == this.getIdResponsable() || null == mObj.getIdResponsable()) return false;
			else return (this.getIdResponsable().equals(mObj.getIdResponsable()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdResponsable()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdResponsable().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}