package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the stage table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="stage"
 */
public abstract class BaseStage  implements Serializable {

	public static String PROP_ID_STAGE = "IdStage";
	public static String PROP_ID_EVENEMENT_LAUREAT = "IdEvenementLaureat";
	public static String PROP_DESCRIPTION_STAGE = "DescriptionStage";
	public static String PROP_DOMAINE_STAGE = "DomaineStage";
	public static String PROP_IMAGE = "Image";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idStage;

	// fields
	private java.lang.String _image;
	private java.lang.String _descriptionStage;
	private java.lang.String _domaineStage;

	// many to one
	private model.Evenementlaureat _idEvenementLaureat;


	// constructors
	public BaseStage () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseStage (java.lang.Integer _idStage) {
		this.setIdStage(_idStage);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseStage (
		java.lang.Integer _idStage,
		model.Evenementlaureat _idEvenementLaureat,
		java.lang.String _image,
		java.lang.String _descriptionStage,
		java.lang.String _domaineStage) {

		this.setIdStage(_idStage);
		this.setIdEvenementLaureat(_idEvenementLaureat);
		this.setImage(_image);
		this.setDescriptionStage(_descriptionStage);
		this.setDomaineStage(_domaineStage);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="idStage"
     */
	public java.lang.Integer getIdStage () {
		return _idStage;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idStage the new ID
	 */
	public void setIdStage (java.lang.Integer _idStage) {
		this._idStage = _idStage;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: image
	 */
	public java.lang.String getImage () {
		return _image;
	}

	/**
	 * Set the value related to the column: image
	 * @param _image the image value
	 */
	public void setImage (java.lang.String _image) {
		this._image = _image;
	}


	/**
	 * Return the value associated with the column: descriptionStage
	 */
	public java.lang.String getDescriptionStage () {
		return _descriptionStage;
	}

	/**
	 * Set the value related to the column: descriptionStage
	 * @param _descriptionStage the descriptionStage value
	 */
	public void setDescriptionStage (java.lang.String _descriptionStage) {
		this._descriptionStage = _descriptionStage;
	}


	/**
	 * Return the value associated with the column: domaineStage
	 */
	public java.lang.String getDomaineStage () {
		return _domaineStage;
	}

	/**
	 * Set the value related to the column: domaineStage
	 * @param _domaineStage the domaineStage value
	 */
	public void setDomaineStage (java.lang.String _domaineStage) {
		this._domaineStage = _domaineStage;
	}


	/**
     * @hibernate.property
     *  column=idEvenementLaureat
	 * not-null=true
	 */
	public model.Evenementlaureat getIdEvenementLaureat () {
		return this._idEvenementLaureat;
	}

	/**
	 * Set the value related to the column: idEvenementLaureat
	 * @param _idEvenementLaureat the idEvenementLaureat value
	 */
	public void setIdEvenementLaureat (model.Evenementlaureat _idEvenementLaureat) {
		this._idEvenementLaureat = _idEvenementLaureat;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseStage)) return false;
		else {
			model.base.BaseStage mObj = (model.base.BaseStage) obj;
			if (null == this.getIdStage() || null == mObj.getIdStage()) return false;
			else return (this.getIdStage().equals(mObj.getIdStage()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdStage()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdStage().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}