package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public class BaseAmitiePK implements Serializable {

	private int hashCode = Integer.MIN_VALUE;

	private model.Laureat _amitierecepteur;
	private model.Laureat _amitieemetteur;

	public BaseAmitiePK () {}
	
	public BaseAmitiePK (
		model.Laureat _amitierecepteur,
		model.Laureat _amitieemetteur) {

		this.setAmitierecepteur(_amitierecepteur);
		this.setAmitieemetteur(_amitieemetteur);
	}


	public model.Laureat getAmitierecepteur () {
		return _amitierecepteur;
	}

	public void setAmitierecepteur (model.Laureat _amitierecepteur) {
		hashCode = Integer.MIN_VALUE;
		this._amitierecepteur = _amitierecepteur;
	}

	public model.Laureat getAmitieemetteur () {
		return _amitieemetteur;
	}

	public void setAmitieemetteur (model.Laureat _amitieemetteur) {
		hashCode = Integer.MIN_VALUE;
		this._amitieemetteur = _amitieemetteur;
	}

	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.AmitiePK)) return false;
		else {
			model.AmitiePK mObj = (model.AmitiePK) obj;
			if (null != this.getAmitierecepteur() && null != mObj.getAmitierecepteur()) {
				if (!this.getAmitierecepteur().equals(mObj.getAmitierecepteur())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getAmitieemetteur() && null != mObj.getAmitieemetteur()) {
				if (!this.getAmitieemetteur().equals(mObj.getAmitieemetteur())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}

	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getAmitierecepteur()) {
				sb.append(this.getAmitierecepteur().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getAmitieemetteur()) {
				sb.append(this.getAmitieemetteur().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}

}