package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the emploi table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="emploi"
 */
public abstract class BaseEmploi  implements Serializable {

	public static String PROP_ID_EVENEMENT_LAUREAT = "IdEvenementLaureat";
	public static String PROP_DESCRIPTION_EMPLOI = "DescriptionEmploi";
	public static String PROP_IMAGE = "Image";
	public static String PROP_DOMAINE_EMPLOI = "DomaineEmploi";
	public static String PROP_ID_EMPLOI = "IdEmploi";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idEmploi;

	// fields
	private java.lang.String _image;
	private java.lang.String _descriptionEmploi;
	private java.lang.String _domaineEmploi;

	// many to one
	private model.Evenementlaureat _idEvenementLaureat;

	// collections
	private java.util.Set _posterSet;


	// constructors
	public BaseEmploi () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseEmploi (java.lang.Integer _idEmploi) {
		this.setIdEmploi(_idEmploi);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseEmploi (
		java.lang.Integer _idEmploi,
		model.Evenementlaureat _idEvenementLaureat,
		java.lang.String _image,
		java.lang.String _descriptionEmploi,
		java.lang.String _domaineEmploi) {

		this.setIdEmploi(_idEmploi);
		this.setIdEvenementLaureat(_idEvenementLaureat);
		this.setImage(_image);
		this.setDescriptionEmploi(_descriptionEmploi);
		this.setDomaineEmploi(_domaineEmploi);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="idEmploi"
     */
	public java.lang.Integer getIdEmploi () {
		return _idEmploi;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idEmploi the new ID
	 */
	public void setIdEmploi (java.lang.Integer _idEmploi) {
		this._idEmploi = _idEmploi;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: image
	 */
	public java.lang.String getImage () {
		return _image;
	}

	/**
	 * Set the value related to the column: image
	 * @param _image the image value
	 */
	public void setImage (java.lang.String _image) {
		this._image = _image;
	}


	/**
	 * Return the value associated with the column: descriptionEmploi
	 */
	public java.lang.String getDescriptionEmploi () {
		return _descriptionEmploi;
	}

	/**
	 * Set the value related to the column: descriptionEmploi
	 * @param _descriptionEmploi the descriptionEmploi value
	 */
	public void setDescriptionEmploi (java.lang.String _descriptionEmploi) {
		this._descriptionEmploi = _descriptionEmploi;
	}


	/**
	 * Return the value associated with the column: domaineEmploi
	 */
	public java.lang.String getDomaineEmploi () {
		return _domaineEmploi;
	}

	/**
	 * Set the value related to the column: domaineEmploi
	 * @param _domaineEmploi the domaineEmploi value
	 */
	public void setDomaineEmploi (java.lang.String _domaineEmploi) {
		this._domaineEmploi = _domaineEmploi;
	}


	/**
     * @hibernate.property
     *  column=idEvenementLaureat
	 * not-null=true
	 */
	public model.Evenementlaureat getIdEvenementLaureat () {
		return this._idEvenementLaureat;
	}

	/**
	 * Set the value related to the column: idEvenementLaureat
	 * @param _idEvenementLaureat the idEvenementLaureat value
	 */
	public void setIdEvenementLaureat (model.Evenementlaureat _idEvenementLaureat) {
		this._idEvenementLaureat = _idEvenementLaureat;
	}


	/**
	 * Return the value associated with the column: PosterSet
	 */
	public java.util.Set getPosterSet () {
		return this._posterSet;
	}

	/**
	 * Set the value related to the column: PosterSet
	 * @param _posterSet the PosterSet value
	 */
	public void setPosterSet (java.util.Set _posterSet) {
		this._posterSet = _posterSet;
	}
	
	public void addToPosterSet (Object obj) {
		if (null == this._posterSet) this._posterSet = new java.util.HashSet();
		this._posterSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseEmploi)) return false;
		else {
			model.base.BaseEmploi mObj = (model.base.BaseEmploi) obj;
			if (null == this.getIdEmploi() || null == mObj.getIdEmploi()) return false;
			else return (this.getIdEmploi().equals(mObj.getIdEmploi()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdEmploi()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdEmploi().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}