package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the messagelaureat table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="messagelaureat"
 */
public abstract class BaseMessagelaureat  implements Serializable {

	public static String PROP_MESSAGE = "Message";
	public static String PROP_HEUREENVOIE = "Heureenvoie";
	public static String PROP_DATEENVOI = "Dateenvoi";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private model.MessagelaureatPK _id;

	// fields
	private java.util.Date _dateenvoi;
	private java.util.Date _heureenvoie;
	private java.lang.String _message;


	// constructors
	public BaseMessagelaureat () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMessagelaureat (model.MessagelaureatPK _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseMessagelaureat (
		model.MessagelaureatPK _id,
		java.util.Date _dateenvoi,
		java.util.Date _heureenvoie,
		java.lang.String _message) {

		this.setId(_id);
		this.setDateenvoi(_dateenvoi);
		this.setHeureenvoie(_heureenvoie);
		this.setMessage(_message);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public model.MessagelaureatPK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (model.MessagelaureatPK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: dateenvoi
	 */
	public java.util.Date getDateenvoi () {
		return _dateenvoi;
	}

	/**
	 * Set the value related to the column: dateenvoi
	 * @param _dateenvoi the dateenvoi value
	 */
	public void setDateenvoi (java.util.Date _dateenvoi) {
		this._dateenvoi = _dateenvoi;
	}


	/**
	 * Return the value associated with the column: Heureenvoie
	 */
	public java.util.Date getHeureenvoie () {
		return _heureenvoie;
	}

	/**
	 * Set the value related to the column: Heureenvoie
	 * @param _heureenvoie the Heureenvoie value
	 */
	public void setHeureenvoie (java.util.Date _heureenvoie) {
		this._heureenvoie = _heureenvoie;
	}


	/**
	 * Return the value associated with the column: message
	 */
	public java.lang.String getMessage () {
		return _message;
	}

	/**
	 * Set the value related to the column: message
	 * @param _message the message value
	 */
	public void setMessage (java.lang.String _message) {
		this._message = _message;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseMessagelaureat)) return false;
		else {
			model.base.BaseMessagelaureat mObj = (model.base.BaseMessagelaureat) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}