package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the laureat table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="laureat"
 */
public abstract class BaseLaureat  implements Serializable {

	public static String PROP_OBJECTIF_ATTEINT = "ObjectifAtteint";
	public static String PROP_OBJECTIF_AVANT_FORM = "ObjectifAvantForm";
	public static String PROP_PARCOURS = "Parcours";
	public static String PROP_INTERET = "Interet";
	public static String PROP_OPTION_CHOISIE = "OptionChoisie";
	public static String PROP_DIPLOME_PREPARE = "DiplomePrepare";
	public static String PROP_RAISON_CONSEIL = "RaisonConseil";
	public static String PROP_FACULTE = "Faculte";
	public static String PROP_ID_LAUREAT = "IdLaureat";
	public static String PROP_CONSEILLER_FORMATION = "ConseillerFormation";
	public static String PROP_ID_PERSONNE = "IdPersonne";
	public static String PROP_COMMENTAIRES = "Commentaires";
	public static String PROP_SITUATION_PRO_AVANT = "SituationProAvant";
	public static String PROP_MATRICULE = "Matricule";
	public static String PROP_TYPE_FORMATION = "TypeFormation";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idLaureat;

	// fields
	private java.lang.String _matricule;
	private java.lang.String _diplomePrepare;
	private java.lang.String _parcours;
	private java.lang.String _optionChoisie;
	private java.lang.String _conseillerFormation;
	private java.lang.String _objectifAvantForm;
	private java.lang.String _raisonConseil;
	private java.lang.String _objectifAtteint;
	private java.lang.String _situationProAvant;
	private java.lang.String _commentaires;
	private java.lang.String _faculte;
	private java.lang.String _typeFormation;
	private java.lang.String _interet;

	// many to one
	private model.Personne _idPersonne;

	// collections
	private java.util.Set _messagemailSet;
	private java.util.Set _commentaireSet;
	private java.util.Set _messagelaureatSetByLaureatrecepteur;
	private java.util.Set _messagelaureatSetByLaureatemetteur;
	private java.util.Set _amitieSetByAmitierecepteur;
	private java.util.Set _evenementlaureatSet;
	private java.util.Set _amitieSetByAmitieemetteur;


	// constructors
	public BaseLaureat () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseLaureat (java.lang.Integer _idLaureat) {
		this.setIdLaureat(_idLaureat);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseLaureat (
		java.lang.Integer _idLaureat,
		model.Personne _idPersonne,
		java.lang.String _matricule,
		java.lang.String _diplomePrepare,
		java.lang.String _parcours,
		java.lang.String _optionChoisie,
		java.lang.String _conseillerFormation,
		java.lang.String _objectifAvantForm,
		java.lang.String _objectifAtteint,
		java.lang.String _situationProAvant,
		java.lang.String _faculte,
		java.lang.String _typeFormation,
		java.lang.String _interet) {

		this.setIdLaureat(_idLaureat);
		this.setIdPersonne(_idPersonne);
		this.setMatricule(_matricule);
		this.setDiplomePrepare(_diplomePrepare);
		this.setParcours(_parcours);
		this.setOptionChoisie(_optionChoisie);
		this.setConseillerFormation(_conseillerFormation);
		this.setObjectifAvantForm(_objectifAvantForm);
		this.setObjectifAtteint(_objectifAtteint);
		this.setSituationProAvant(_situationProAvant);
		this.setFaculte(_faculte);
		this.setTypeFormation(_typeFormation);
		this.setInteret(_interet);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="idLaureat"
     */
	public java.lang.Integer getIdLaureat () {
		return _idLaureat;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idLaureat the new ID
	 */
	public void setIdLaureat (java.lang.Integer _idLaureat) {
		this._idLaureat = _idLaureat;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: matricule
	 */
	public java.lang.String getMatricule () {
		return _matricule;
	}

	/**
	 * Set the value related to the column: matricule
	 * @param _matricule the matricule value
	 */
	public void setMatricule (java.lang.String _matricule) {
		this._matricule = _matricule;
	}


	/**
	 * Return the value associated with the column: diplomePrepare
	 */
	public java.lang.String getDiplomePrepare () {
		return _diplomePrepare;
	}

	/**
	 * Set the value related to the column: diplomePrepare
	 * @param _diplomePrepare the diplomePrepare value
	 */
	public void setDiplomePrepare (java.lang.String _diplomePrepare) {
		this._diplomePrepare = _diplomePrepare;
	}


	/**
	 * Return the value associated with the column: parcours
	 */
	public java.lang.String getParcours () {
		return _parcours;
	}

	/**
	 * Set the value related to the column: parcours
	 * @param _parcours the parcours value
	 */
	public void setParcours (java.lang.String _parcours) {
		this._parcours = _parcours;
	}


	/**
	 * Return the value associated with the column: optionChoisie
	 */
	public java.lang.String getOptionChoisie () {
		return _optionChoisie;
	}

	/**
	 * Set the value related to the column: optionChoisie
	 * @param _optionChoisie the optionChoisie value
	 */
	public void setOptionChoisie (java.lang.String _optionChoisie) {
		this._optionChoisie = _optionChoisie;
	}


	/**
	 * Return the value associated with the column: conseillerFormation
	 */
	public java.lang.String getConseillerFormation () {
		return _conseillerFormation;
	}

	/**
	 * Set the value related to the column: conseillerFormation
	 * @param _conseillerFormation the conseillerFormation value
	 */
	public void setConseillerFormation (java.lang.String _conseillerFormation) {
		this._conseillerFormation = _conseillerFormation;
	}


	/**
	 * Return the value associated with the column: objectifAvantForm
	 */
	public java.lang.String getObjectifAvantForm () {
		return _objectifAvantForm;
	}

	/**
	 * Set the value related to the column: objectifAvantForm
	 * @param _objectifAvantForm the objectifAvantForm value
	 */
	public void setObjectifAvantForm (java.lang.String _objectifAvantForm) {
		this._objectifAvantForm = _objectifAvantForm;
	}


	/**
	 * Return the value associated with the column: raisonConseil
	 */
	public java.lang.String getRaisonConseil () {
		return _raisonConseil;
	}

	/**
	 * Set the value related to the column: raisonConseil
	 * @param _raisonConseil the raisonConseil value
	 */
	public void setRaisonConseil (java.lang.String _raisonConseil) {
		this._raisonConseil = _raisonConseil;
	}


	/**
	 * Return the value associated with the column: objectifAtteint
	 */
	public java.lang.String getObjectifAtteint () {
		return _objectifAtteint;
	}

	/**
	 * Set the value related to the column: objectifAtteint
	 * @param _objectifAtteint the objectifAtteint value
	 */
	public void setObjectifAtteint (java.lang.String _objectifAtteint) {
		this._objectifAtteint = _objectifAtteint;
	}


	/**
	 * Return the value associated with the column: situationProAvant
	 */
	public java.lang.String getSituationProAvant () {
		return _situationProAvant;
	}

	/**
	 * Set the value related to the column: situationProAvant
	 * @param _situationProAvant the situationProAvant value
	 */
	public void setSituationProAvant (java.lang.String _situationProAvant) {
		this._situationProAvant = _situationProAvant;
	}


	/**
	 * Return the value associated with the column: commentaires
	 */
	public java.lang.String getCommentaires () {
		return _commentaires;
	}

	/**
	 * Set the value related to the column: commentaires
	 * @param _commentaires the commentaires value
	 */
	public void setCommentaires (java.lang.String _commentaires) {
		this._commentaires = _commentaires;
	}


	/**
	 * Return the value associated with the column: faculte
	 */
	public java.lang.String getFaculte () {
		return _faculte;
	}

	/**
	 * Set the value related to the column: faculte
	 * @param _faculte the faculte value
	 */
	public void setFaculte (java.lang.String _faculte) {
		this._faculte = _faculte;
	}


	/**
	 * Return the value associated with the column: typeFormation
	 */
	public java.lang.String getTypeFormation () {
		return _typeFormation;
	}

	/**
	 * Set the value related to the column: typeFormation
	 * @param _typeFormation the typeFormation value
	 */
	public void setTypeFormation (java.lang.String _typeFormation) {
		this._typeFormation = _typeFormation;
	}


	/**
	 * Return the value associated with the column: interet
	 */
	public java.lang.String getInteret () {
		return _interet;
	}

	/**
	 * Set the value related to the column: interet
	 * @param _interet the interet value
	 */
	public void setInteret (java.lang.String _interet) {
		this._interet = _interet;
	}


	/**
     * @hibernate.property
     *  column=idPersonne
	 * not-null=true
	 */
	public model.Personne getIdPersonne () {
		return this._idPersonne;
	}

	/**
	 * Set the value related to the column: idPersonne
	 * @param _idPersonne the idPersonne value
	 */
	public void setIdPersonne (model.Personne _idPersonne) {
		this._idPersonne = _idPersonne;
	}


	/**
	 * Return the value associated with the column: MessagemailSet
	 */
	public java.util.Set getMessagemailSet () {
		return this._messagemailSet;
	}

	/**
	 * Set the value related to the column: MessagemailSet
	 * @param _messagemailSet the MessagemailSet value
	 */
	public void setMessagemailSet (java.util.Set _messagemailSet) {
		this._messagemailSet = _messagemailSet;
	}
	
	public void addToMessagemailSet (Object obj) {
		if (null == this._messagemailSet) this._messagemailSet = new java.util.HashSet();
		this._messagemailSet.add(obj);
	}



	/**
	 * Return the value associated with the column: CommentaireSet
	 */
	public java.util.Set getCommentaireSet () {
		return this._commentaireSet;
	}

	/**
	 * Set the value related to the column: CommentaireSet
	 * @param _commentaireSet the CommentaireSet value
	 */
	public void setCommentaireSet (java.util.Set _commentaireSet) {
		this._commentaireSet = _commentaireSet;
	}
	
	public void addToCommentaireSet (Object obj) {
		if (null == this._commentaireSet) this._commentaireSet = new java.util.HashSet();
		this._commentaireSet.add(obj);
	}



	/**
	 * Return the value associated with the column: MessagelaureatSetByLaureatrecepteur
	 */
	public java.util.Set getMessagelaureatSetByLaureatrecepteur () {
		return this._messagelaureatSetByLaureatrecepteur;
	}

	/**
	 * Set the value related to the column: MessagelaureatSetByLaureatrecepteur
	 * @param _messagelaureatSetByLaureatrecepteur the MessagelaureatSetByLaureatrecepteur value
	 */
	public void setMessagelaureatSetByLaureatrecepteur (java.util.Set _messagelaureatSetByLaureatrecepteur) {
		this._messagelaureatSetByLaureatrecepteur = _messagelaureatSetByLaureatrecepteur;
	}
	
	public void addToMessagelaureatSetByLaureatrecepteur (Object obj) {
		if (null == this._messagelaureatSetByLaureatrecepteur) this._messagelaureatSetByLaureatrecepteur = new java.util.HashSet();
		this._messagelaureatSetByLaureatrecepteur.add(obj);
	}



	/**
	 * Return the value associated with the column: MessagelaureatSetByLaureatemetteur
	 */
	public java.util.Set getMessagelaureatSetByLaureatemetteur () {
		return this._messagelaureatSetByLaureatemetteur;
	}

	/**
	 * Set the value related to the column: MessagelaureatSetByLaureatemetteur
	 * @param _messagelaureatSetByLaureatemetteur the MessagelaureatSetByLaureatemetteur value
	 */
	public void setMessagelaureatSetByLaureatemetteur (java.util.Set _messagelaureatSetByLaureatemetteur) {
		this._messagelaureatSetByLaureatemetteur = _messagelaureatSetByLaureatemetteur;
	}
	
	public void addToMessagelaureatSetByLaureatemetteur (Object obj) {
		if (null == this._messagelaureatSetByLaureatemetteur) this._messagelaureatSetByLaureatemetteur = new java.util.HashSet();
		this._messagelaureatSetByLaureatemetteur.add(obj);
	}



	/**
	 * Return the value associated with the column: AmitieSetByAmitierecepteur
	 */
	public java.util.Set getAmitieSetByAmitierecepteur () {
		return this._amitieSetByAmitierecepteur;
	}

	/**
	 * Set the value related to the column: AmitieSetByAmitierecepteur
	 * @param _amitieSetByAmitierecepteur the AmitieSetByAmitierecepteur value
	 */
	public void setAmitieSetByAmitierecepteur (java.util.Set _amitieSetByAmitierecepteur) {
		this._amitieSetByAmitierecepteur = _amitieSetByAmitierecepteur;
	}
	
	public void addToAmitieSetByAmitierecepteur (Object obj) {
		if (null == this._amitieSetByAmitierecepteur) this._amitieSetByAmitierecepteur = new java.util.HashSet();
		this._amitieSetByAmitierecepteur.add(obj);
	}



	/**
	 * Return the value associated with the column: EvenementlaureatSet
	 */
	public java.util.Set getEvenementlaureatSet () {
		return this._evenementlaureatSet;
	}

	/**
	 * Set the value related to the column: EvenementlaureatSet
	 * @param _evenementlaureatSet the EvenementlaureatSet value
	 */
	public void setEvenementlaureatSet (java.util.Set _evenementlaureatSet) {
		this._evenementlaureatSet = _evenementlaureatSet;
	}
	
	public void addToEvenementlaureatSet (Object obj) {
		if (null == this._evenementlaureatSet) this._evenementlaureatSet = new java.util.HashSet();
		this._evenementlaureatSet.add(obj);
	}



	/**
	 * Return the value associated with the column: AmitieSetByAmitieemetteur
	 */
	public java.util.Set getAmitieSetByAmitieemetteur () {
		return this._amitieSetByAmitieemetteur;
	}

	/**
	 * Set the value related to the column: AmitieSetByAmitieemetteur
	 * @param _amitieSetByAmitieemetteur the AmitieSetByAmitieemetteur value
	 */
	public void setAmitieSetByAmitieemetteur (java.util.Set _amitieSetByAmitieemetteur) {
		this._amitieSetByAmitieemetteur = _amitieSetByAmitieemetteur;
	}
	
	public void addToAmitieSetByAmitieemetteur (Object obj) {
		if (null == this._amitieSetByAmitieemetteur) this._amitieSetByAmitieemetteur = new java.util.HashSet();
		this._amitieSetByAmitieemetteur.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseLaureat)) return false;
		else {
			model.base.BaseLaureat mObj = (model.base.BaseLaureat) obj;
			if (null == this.getIdLaureat() || null == mObj.getIdLaureat()) return false;
			else return (this.getIdLaureat().equals(mObj.getIdLaureat()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdLaureat()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdLaureat().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}