package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the commentaire table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="commentaire"
 */
public abstract class BaseCommentaire  implements Serializable {

	public static String PROP_ID_LAUREAT = "IdLaureat";
	public static String PROP_TEXTE = "Texte";
	public static String PROP_ID_PROGRAMME_FORMATION = "IdProgrammeFormation";
	public static String PROP_HEURE = "Heure";
	public static String PROP_ID_COMMENTAIRE = "IdCommentaire";
	public static String PROP_DATE = "Date";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idCommentaire;

	// fields
	private java.util.Date _date;
	private java.util.Date _heure;
	private java.lang.Integer _idProgrammeFormation;
	private java.lang.String _texte;

	// many to one
	private model.Laureat _idLaureat;


	// constructors
	public BaseCommentaire () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCommentaire (java.lang.Integer _idCommentaire) {
		this.setIdCommentaire(_idCommentaire);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCommentaire (
		java.lang.Integer _idCommentaire,
		model.Laureat _idLaureat,
		java.util.Date _date,
		java.util.Date _heure,
		java.lang.Integer _idProgrammeFormation,
		java.lang.String _texte) {

		this.setIdCommentaire(_idCommentaire);
		this.setIdLaureat(_idLaureat);
		this.setDate(_date);
		this.setHeure(_heure);
		this.setIdProgrammeFormation(_idProgrammeFormation);
		this.setTexte(_texte);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="idCommentaire"
     */
	public java.lang.Integer getIdCommentaire () {
		return _idCommentaire;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idCommentaire the new ID
	 */
	public void setIdCommentaire (java.lang.Integer _idCommentaire) {
		this._idCommentaire = _idCommentaire;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: date
	 */
	public java.util.Date getDate () {
		return _date;
	}

	/**
	 * Set the value related to the column: date
	 * @param _date the date value
	 */
	public void setDate (java.util.Date _date) {
		this._date = _date;
	}


	/**
	 * Return the value associated with the column: heure
	 */
	public java.util.Date getHeure () {
		return _heure;
	}

	/**
	 * Set the value related to the column: heure
	 * @param _heure the heure value
	 */
	public void setHeure (java.util.Date _heure) {
		this._heure = _heure;
	}


	/**
	 * Return the value associated with the column: idProgrammeFormation
	 */
	public java.lang.Integer getIdProgrammeFormation () {
		return _idProgrammeFormation;
	}

	/**
	 * Set the value related to the column: idProgrammeFormation
	 * @param _idProgrammeFormation the idProgrammeFormation value
	 */
	public void setIdProgrammeFormation (java.lang.Integer _idProgrammeFormation) {
		this._idProgrammeFormation = _idProgrammeFormation;
	}


	/**
	 * Return the value associated with the column: texte
	 */
	public java.lang.String getTexte () {
		return _texte;
	}

	/**
	 * Set the value related to the column: texte
	 * @param _texte the texte value
	 */
	public void setTexte (java.lang.String _texte) {
		this._texte = _texte;
	}


	/**
     * @hibernate.property
     *  column=idLaureat
	 * not-null=true
	 */
	public model.Laureat getIdLaureat () {
		return this._idLaureat;
	}

	/**
	 * Set the value related to the column: idLaureat
	 * @param _idLaureat the idLaureat value
	 */
	public void setIdLaureat (model.Laureat _idLaureat) {
		this._idLaureat = _idLaureat;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseCommentaire)) return false;
		else {
			model.base.BaseCommentaire mObj = (model.base.BaseCommentaire) obj;
			if (null == this.getIdCommentaire() || null == mObj.getIdCommentaire()) return false;
			else return (this.getIdCommentaire().equals(mObj.getIdCommentaire()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdCommentaire()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdCommentaire().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}