package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the messagemail table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="messagemail"
 */
public abstract class BaseMessagemail  implements Serializable {

	public static String PROP_DATEENVOIE = "Dateenvoie";
	public static String PROP_HEUREENVOIE = "Heureenvoie";
	public static String PROP_TEXTE = "Texte";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private model.MessagemailPK _id;

	// fields
	private java.util.Date _heureenvoie;
	private java.util.Date _dateenvoie;
	private java.lang.String _texte;


	// constructors
	public BaseMessagemail () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMessagemail (model.MessagemailPK _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseMessagemail (
		model.MessagemailPK _id,
		java.util.Date _heureenvoie,
		java.util.Date _dateenvoie,
		java.lang.String _texte) {

		this.setId(_id);
		this.setHeureenvoie(_heureenvoie);
		this.setDateenvoie(_dateenvoie);
		this.setTexte(_texte);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public model.MessagemailPK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (model.MessagemailPK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Heureenvoie
	 */
	public java.util.Date getHeureenvoie () {
		return _heureenvoie;
	}

	/**
	 * Set the value related to the column: Heureenvoie
	 * @param _heureenvoie the Heureenvoie value
	 */
	public void setHeureenvoie (java.util.Date _heureenvoie) {
		this._heureenvoie = _heureenvoie;
	}


	/**
	 * Return the value associated with the column: dateenvoie
	 */
	public java.util.Date getDateenvoie () {
		return _dateenvoie;
	}

	/**
	 * Set the value related to the column: dateenvoie
	 * @param _dateenvoie the dateenvoie value
	 */
	public void setDateenvoie (java.util.Date _dateenvoie) {
		this._dateenvoie = _dateenvoie;
	}


	/**
	 * Return the value associated with the column: texte
	 */
	public java.lang.String getTexte () {
		return _texte;
	}

	/**
	 * Set the value related to the column: texte
	 * @param _texte the texte value
	 */
	public void setTexte (java.lang.String _texte) {
		this._texte = _texte;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseMessagemail)) return false;
		else {
			model.base.BaseMessagemail mObj = (model.base.BaseMessagemail) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}