package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the programmeformation table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="programmeformation"
 */
public abstract class BaseProgrammeformation  implements Serializable {

	public static String PROP_SUGGESTION = "Suggestion";
	public static String PROP_ID_EVENEMENT_LAUREAT = "IdEvenementLaureat";
	public static String PROP_JUSTIFICATIF = "Justificatif";
	public static String PROP_ID_PROGRAMME_FORMATION = "IdProgrammeFormation";
	public static String PROP_IMAGE = "Image";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idProgrammeFormation;

	// fields
	private java.lang.String _image;
	private java.lang.String _suggestion;
	private java.lang.String _justificatif;

	// many to one
	private model.Evenementlaureat _idEvenementLaureat;


	// constructors
	public BaseProgrammeformation () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseProgrammeformation (java.lang.Integer _idProgrammeFormation) {
		this.setIdProgrammeFormation(_idProgrammeFormation);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseProgrammeformation (
		java.lang.Integer _idProgrammeFormation,
		model.Evenementlaureat _idEvenementLaureat,
		java.lang.String _image,
		java.lang.String _suggestion,
		java.lang.String _justificatif) {

		this.setIdProgrammeFormation(_idProgrammeFormation);
		this.setIdEvenementLaureat(_idEvenementLaureat);
		this.setImage(_image);
		this.setSuggestion(_suggestion);
		this.setJustificatif(_justificatif);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="idProgrammeFormation"
     */
	public java.lang.Integer getIdProgrammeFormation () {
		return _idProgrammeFormation;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idProgrammeFormation the new ID
	 */
	public void setIdProgrammeFormation (java.lang.Integer _idProgrammeFormation) {
		this._idProgrammeFormation = _idProgrammeFormation;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: image
	 */
	public java.lang.String getImage () {
		return _image;
	}

	/**
	 * Set the value related to the column: image
	 * @param _image the image value
	 */
	public void setImage (java.lang.String _image) {
		this._image = _image;
	}


	/**
	 * Return the value associated with the column: suggestion
	 */
	public java.lang.String getSuggestion () {
		return _suggestion;
	}

	/**
	 * Set the value related to the column: suggestion
	 * @param _suggestion the suggestion value
	 */
	public void setSuggestion (java.lang.String _suggestion) {
		this._suggestion = _suggestion;
	}


	/**
	 * Return the value associated with the column: justificatif
	 */
	public java.lang.String getJustificatif () {
		return _justificatif;
	}

	/**
	 * Set the value related to the column: justificatif
	 * @param _justificatif the justificatif value
	 */
	public void setJustificatif (java.lang.String _justificatif) {
		this._justificatif = _justificatif;
	}


	/**
     * @hibernate.property
     *  column=idEvenementLaureat
	 * not-null=true
	 */
	public model.Evenementlaureat getIdEvenementLaureat () {
		return this._idEvenementLaureat;
	}

	/**
	 * Set the value related to the column: idEvenementLaureat
	 * @param _idEvenementLaureat the idEvenementLaureat value
	 */
	public void setIdEvenementLaureat (model.Evenementlaureat _idEvenementLaureat) {
		this._idEvenementLaureat = _idEvenementLaureat;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseProgrammeformation)) return false;
		else {
			model.base.BaseProgrammeformation mObj = (model.base.BaseProgrammeformation) obj;
			if (null == this.getIdProgrammeFormation() || null == mObj.getIdProgrammeFormation()) return false;
			else return (this.getIdProgrammeFormation().equals(mObj.getIdProgrammeFormation()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdProgrammeFormation()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdProgrammeFormation().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}