package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the evenementlaureat table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="evenementlaureat"
 */
public abstract class BaseEvenementlaureat  implements Serializable {

	public static String PROP_DATE_PUBLICATION = "DatePublication";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_ID_EVENEMENT_LAUREAT = "IdEvenementLaureat";
	public static String PROP_NOM_EVENEMENT = "NomEvenement";
	public static String PROP_ID_LAUREAT = "IdLaureat";
	public static String PROP_HEURE_PUBLICATION = "HeurePublication";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idEvenementLaureat;

	// fields
	private java.lang.String _nomEvenement;
	private java.util.Date _heurePublication;
	private java.util.Date _datePublication;
	private java.lang.String _description;

	// many to one
	private model.Laureat _idLaureat;

	// collections
	private java.util.Set _emploiSet;
	private java.util.Set _donSet;
	private java.util.Set _programmeformationSet;
	private java.util.Set _stageSet;


	// constructors
	public BaseEvenementlaureat () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseEvenementlaureat (java.lang.Integer _idEvenementLaureat) {
		this.setIdEvenementLaureat(_idEvenementLaureat);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseEvenementlaureat (
		java.lang.Integer _idEvenementLaureat,
		model.Laureat _idLaureat,
		java.lang.String _nomEvenement,
		java.util.Date _heurePublication,
		java.util.Date _datePublication,
		java.lang.String _description) {

		this.setIdEvenementLaureat(_idEvenementLaureat);
		this.setIdLaureat(_idLaureat);
		this.setNomEvenement(_nomEvenement);
		this.setHeurePublication(_heurePublication);
		this.setDatePublication(_datePublication);
		this.setDescription(_description);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="idEvenementLaureat"
     */
	public java.lang.Integer getIdEvenementLaureat () {
		return _idEvenementLaureat;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idEvenementLaureat the new ID
	 */
	public void setIdEvenementLaureat (java.lang.Integer _idEvenementLaureat) {
		this._idEvenementLaureat = _idEvenementLaureat;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: nomEvenement
	 */
	public java.lang.String getNomEvenement () {
		return _nomEvenement;
	}

	/**
	 * Set the value related to the column: nomEvenement
	 * @param _nomEvenement the nomEvenement value
	 */
	public void setNomEvenement (java.lang.String _nomEvenement) {
		this._nomEvenement = _nomEvenement;
	}


	/**
	 * Return the value associated with the column: heurePublication
	 */
	public java.util.Date getHeurePublication () {
		return _heurePublication;
	}

	/**
	 * Set the value related to the column: heurePublication
	 * @param _heurePublication the heurePublication value
	 */
	public void setHeurePublication (java.util.Date _heurePublication) {
		this._heurePublication = _heurePublication;
	}


	/**
	 * Return the value associated with the column: datePublication
	 */
	public java.util.Date getDatePublication () {
		return _datePublication;
	}

	/**
	 * Set the value related to the column: datePublication
	 * @param _datePublication the datePublication value
	 */
	public void setDatePublication (java.util.Date _datePublication) {
		this._datePublication = _datePublication;
	}


	/**
	 * Return the value associated with the column: description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: description
	 * @param _description the description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
     * @hibernate.property
     *  column=idLaureat
	 * not-null=true
	 */
	public model.Laureat getIdLaureat () {
		return this._idLaureat;
	}

	/**
	 * Set the value related to the column: idLaureat
	 * @param _idLaureat the idLaureat value
	 */
	public void setIdLaureat (model.Laureat _idLaureat) {
		this._idLaureat = _idLaureat;
	}


	/**
	 * Return the value associated with the column: EmploiSet
	 */
	public java.util.Set getEmploiSet () {
		return this._emploiSet;
	}

	/**
	 * Set the value related to the column: EmploiSet
	 * @param _emploiSet the EmploiSet value
	 */
	public void setEmploiSet (java.util.Set _emploiSet) {
		this._emploiSet = _emploiSet;
	}
	
	public void addToEmploiSet (Object obj) {
		if (null == this._emploiSet) this._emploiSet = new java.util.HashSet();
		this._emploiSet.add(obj);
	}



	/**
	 * Return the value associated with the column: DonSet
	 */
	public java.util.Set getDonSet () {
		return this._donSet;
	}

	/**
	 * Set the value related to the column: DonSet
	 * @param _donSet the DonSet value
	 */
	public void setDonSet (java.util.Set _donSet) {
		this._donSet = _donSet;
	}
	
	public void addToDonSet (Object obj) {
		if (null == this._donSet) this._donSet = new java.util.HashSet();
		this._donSet.add(obj);
	}



	/**
	 * Return the value associated with the column: ProgrammeformationSet
	 */
	public java.util.Set getProgrammeformationSet () {
		return this._programmeformationSet;
	}

	/**
	 * Set the value related to the column: ProgrammeformationSet
	 * @param _programmeformationSet the ProgrammeformationSet value
	 */
	public void setProgrammeformationSet (java.util.Set _programmeformationSet) {
		this._programmeformationSet = _programmeformationSet;
	}
	
	public void addToProgrammeformationSet (Object obj) {
		if (null == this._programmeformationSet) this._programmeformationSet = new java.util.HashSet();
		this._programmeformationSet.add(obj);
	}



	/**
	 * Return the value associated with the column: StageSet
	 */
	public java.util.Set getStageSet () {
		return this._stageSet;
	}

	/**
	 * Set the value related to the column: StageSet
	 * @param _stageSet the StageSet value
	 */
	public void setStageSet (java.util.Set _stageSet) {
		this._stageSet = _stageSet;
	}
	
	public void addToStageSet (Object obj) {
		if (null == this._stageSet) this._stageSet = new java.util.HashSet();
		this._stageSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseEvenementlaureat)) return false;
		else {
			model.base.BaseEvenementlaureat mObj = (model.base.BaseEvenementlaureat) obj;
			if (null == this.getIdEvenementLaureat() || null == mObj.getIdEvenementLaureat()) return false;
			else return (this.getIdEvenementLaureat().equals(mObj.getIdEvenementLaureat()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdEvenementLaureat()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdEvenementLaureat().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}